development: &default
  adapter: postgresql
  database: rdae
  encoding: utf8
  pool: 5

test:
  <<: *default
  database: rdae_test

staging:
  <<: *default
  database: rdae_staging

production:
  <<: *default
  database: rdae
